
package uk.gov.dcsf.ispp.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import uk.gov.dcsf.ispp.webservice.encodedtypes.ObjectFactory;
import uk.gov.dcsf.ispp.webservice.encodedtypes.UploadRequestT;
import uk.gov.dcsf.ispp.webservice.encodedtypes.UploadResponseT;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISPPPortType", targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISPPPortType {


    /**
     * 
     * @param doc
     * @return
     *     returns uk.gov.dcsf.ispp.webservice.encodedtypes.UploadResponseT
     */
    @WebMethod
    @WebResult(name = "uploadResponse", targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice/encodedTypes", partName = "result")
    public UploadResponseT upload(
        @WebParam(name = "uploadRequest", targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice/encodedTypes", partName = "doc")
        UploadRequestT doc);

}
