
package uk.gov.dcsf.ispp.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISPPDepositImplService", targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice", wsdlLocation = "file:/home/ibbo/dev/VirtualFIS/soap2/metroisppsoap/deposit.wsdl")
public class ISPPDepositImplService
    extends Service
{

    private final static URL ISPPDEPOSITIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISPPDEPOSITIMPLSERVICE_EXCEPTION;
    private final static QName ISPPDEPOSITIMPLSERVICE_QNAME = new QName("http://dcsf.gov.uk/ISPP/Webservice", "ISPPDepositImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/ibbo/dev/VirtualFIS/soap2/metroisppsoap/deposit.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISPPDEPOSITIMPLSERVICE_WSDL_LOCATION = url;
        ISPPDEPOSITIMPLSERVICE_EXCEPTION = e;
    }

    public ISPPDepositImplService() {
        super(__getWsdlLocation(), ISPPDEPOSITIMPLSERVICE_QNAME);
    }

    public ISPPDepositImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISPPDEPOSITIMPLSERVICE_QNAME, features);
    }

    public ISPPDepositImplService(URL wsdlLocation) {
        super(wsdlLocation, ISPPDEPOSITIMPLSERVICE_QNAME);
    }

    public ISPPDepositImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISPPDEPOSITIMPLSERVICE_QNAME, features);
    }

    public ISPPDepositImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISPPDepositImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISPPPortType
     */
    @WebEndpoint(name = "ISPPPortTypePort")
    public ISPPPortType getISPPPortTypePort() {
        return super.getPort(new QName("http://dcsf.gov.uk/ISPP/Webservice", "ISPPPortTypePort"), ISPPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISPPPortType
     */
    @WebEndpoint(name = "ISPPPortTypePort")
    public ISPPPortType getISPPPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dcsf.gov.uk/ISPP/Webservice", "ISPPPortTypePort"), ISPPPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISPPDEPOSITIMPLSERVICE_EXCEPTION!= null) {
            throw ISPPDEPOSITIMPLSERVICE_EXCEPTION;
        }
        return ISPPDEPOSITIMPLSERVICE_WSDL_LOCATION;
    }

}
