package org.grails.cxf.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-22T17:45:36.638Z
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ISPPDepositImplService", 
                  wsdlLocation = "deposit.wsdl",
                  targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice") 
public class ISPPDepositImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dcsf.gov.uk/ISPP/Webservice", "ISPPDepositImplService");
    public final static QName ISPPPortTypePort = new QName("http://dcsf.gov.uk/ISPP/Webservice", "ISPPPortTypePort");
    static {
        URL url = ISPPDepositImplService.class.getResource("deposit.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ISPPDepositImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "deposit.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ISPPDepositImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISPPDepositImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISPPDepositImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISPPDepositImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISPPDepositImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISPPDepositImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ISPPPortType
     */
    @WebEndpoint(name = "ISPPPortTypePort")
    public ISPPPortType getISPPPortTypePort() {
        return super.getPort(ISPPPortTypePort, ISPPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISPPPortType
     */
    @WebEndpoint(name = "ISPPPortTypePort")
    public ISPPPortType getISPPPortTypePort(WebServiceFeature... features) {
        return super.getPort(ISPPPortTypePort, ISPPPortType.class, features);
    }

}
