package org.grails.cxf.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-22T17:45:36.596Z
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice", name = "ISPPPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ISPPPortType {

    @WebResult(name = "uploadResponse", targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice/encodedTypes", partName = "result")
    @WebMethod
    public UploadResponseT upload(
        @WebParam(partName = "doc", name = "uploadRequest", targetNamespace = "http://dcsf.gov.uk/ISPP/Webservice/encodedTypes")
        UploadRequestT doc
    );
}
